### PR TITLE
Hints

### LINKED ISSUE #2: Dynamic hints
[Img](https://www.puzzlesbrain.com/wp-content/uploads/2017/07/crack-the-code-682-738-780-puzzle-answer.png) 
- One correct and well placed
- One correct and wrong placed
- Two correct and wrong placed
- Nothing correct

### PR DESCRIPTION
**Pull request by madiote**
Fixes #2 

Currently displays them in logcat, UI integration is needed.

pilt

### CODE REVIEW

File: app/src/main/java/com/example/codemystery/MainActivity.java [hunk 1]
```diff
@@ -122,6 +133,21 @@ public void run()
 
     }
 
+    private static int getRandomNumberInRange(int min, int max) { // https://mkyong.com/java/java-generate-random-integers-in-a-range/
+        if (min >= max) {
```
Comment (mihkelva) [inline app/src/main/java/com/example/codemystery/MainActivity.java:137]: Kas on vajalik?  min ja max hard-coded
